OrdererOrgs:
  - Name: R4
    Domain: demo.com
    Specs:
      - Hostname: o4

PeerOrgs:
  - Name: R1
    Domain: r1.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
  - Name: R2
    Domain: r2.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2